apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
  labels:
    app: nginx-ingress-controller
spec:
  type: NodePort
  selector:
    app: nginx-ingress-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-ssl
  namespace: kube-system
  labels:
    app: nginx-ingress-controller
spec:
  type: NodePort
  selector:
    app: nginx-ingress-controller
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress-controller
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
    spec:
      containers:
        - name: nginx-ingress-controller
          image: nginx/nginx-ingress-controller:latest
          args:
            - /nginx-ingress-controller
            - "--configmap=$(POD_NAMESPACE)/nginx-ingress-controller-conf"
            - "--tcp-services-configmap=$(POD_NAMESPACE)/tcp-services"
            - "--udp-services-configmap=$(POD_NAMESPACE)/udp-services"
            - "--publish-service=$(POD_NAMESPACE)/nginx-ingress-controller
